apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: influxdb
    spec:
      containers:
        - env:
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "false"
            - name: INFLUXDB_HTTP_FLUX_ENABLED
              value: "false"
            - name: INFLUXDB_MONITOR_STORE_ENABLED
              value: "FALSE"
            - name: INFLUXDB_REPORTING_DISABLED
              value: "false"
            - name: TZ
              value: Etc/UTC
          image: influxdb:1.8
          livenessProbe:
            exec:
              command:
                - curl
                - http://localhost:8086
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: influxdb
          ports:
            - containerPort: 8086
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-claim0
            - mountPath: /var/lib/influxdb/backup
              name: influxdb-claim1
      restartPolicy: Always
      volumes:
        - name: influxdb-claim0
          persistentVolumeClaim:
            claimName: influxdb-claim0
        - name: influxdb-claim1
          persistentVolumeClaim:
            claimName: influxdb-claim1
status: {}
