apiVersion: v1
kind: Service
metadata:
  name: lstm-service
  labels:
    io.kompose.service: lstm
spec:
  selector:
    app: lstm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # replace with the port your application uses
  type: LoadBalancer

