apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: mosquitto
    spec:
      containers:
        - env:
            - name: TZ
              value: Etc/UTC
          image: mosquitto
          name: mosquitto
          ports:
            - containerPort: 1883
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto-claim0
            - mountPath: /mosquitto/data
              name: mosquitto-claim1
            - mountPath: /mosquitto/log
              name: mosquitto-claim2
            - mountPath: /mosquitto/pwfile
              name: mosquitto-claim3
      restartPolicy: Always
      volumes:
        - name: mosquitto-claim0
          persistentVolumeClaim:
            claimName: mosquitto-claim0
        - name: mosquitto-claim1
          persistentVolumeClaim:
            claimName: mosquitto-claim1
        - name: mosquitto-claim2
          persistentVolumeClaim:
            claimName: mosquitto-claim2
        - name: mosquitto-claim3
          persistentVolumeClaim:
            claimName: mosquitto-claim3
status: {}
