apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: qemu-rpi-os-sensor
  name: qemu-rpi-os-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qemu-rpi-os-sensor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: qemu-rpi-os-sensor
    spec:
      containers:
        - image: ghcr.io/mohamed9974/rpi-os-custom-image-with-sensors/qemu-rpi-os-sensor:latest
          name: qemu-rpi-os-sensor
          ports:
            - containerPort: 5022
          resources: {}
      restartPolicy: Always
status: {}
