domoticz:
  container_name: domoticz
  image: lscr.io/linuxserver/domoticz:latest
  ports:
    - "8083:8080"
    - "6144:6144"
    - "1443:1443"
  volumes:
    - ./volumes/domoticz/data:/config
  restart: unless-stopped
  environment:
    - PUID=1000
    - PGID=1000
    # - TZ=Etc/UTC
    # - WEBROOT=domoticz

