name: telegraf-s
version: 1.8.1
description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics.
keywords:
- telegraf
- collector
- timeseries
- influxdata
home: https://www.influxdata.com/time-series-platform/telegraf/
maintainers:
- name: mohamed aly amin
  email: contact@mohamedalyamin.com 
apiVersion: v2