apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
    component: config
data:
  grafana.ini: |
    [server]
    domain = k8s-leader.ceng.metu.edu.tr
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true

